site_name: Reconmap docs

site_url: https://docs.reconmap.com
repo_url: https://github.com/reconmap/documentation
edit_uri: edit/main/docs/

theme:
  name: material

  logo: images/icon-512.png
  favicon: images/favicon.ico

  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
  palette: 
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - git-revision-date-localized:
      enable_creation_date: false

extra:
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/reconmap
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/reconmap/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences