site_name: Reconmap docs

repo_url: https://github.com/reconmap/documentation

theme:
  name: material

  logo: images/icon-512.png
  favicon: images/favicon.ico

  features:
    - navigation.path
    - content.code.copy
  palette: 
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences